import { existsSync } from "node:fs";
import path from "node:path";
import { migrate as migratePglite } from "drizzle-orm/pglite/migrator";
import { migrate as migratePostgres } from "drizzle-orm/postgres-js/migrator";
import { getDb, isHostedDb } from "./client";

const MIGRATIONS = path.join(process.cwd(), "drizzle");

// Applies every file in drizzle/meta/_journal.json in order: 0000_init.sql (generated by
// `npm run db:generate`), 0001_rules.sql (hand-written triggers and the task_outcome view),
// 0002_ask.sql and 0003_rls.sql. Safe to call on every start: drizzle records applied migrations and skips them.
// The migrator must match the driver behind getDb(), so DATABASE_URL picks it.
export async function runMigrations() {
  if (!existsSync(path.join(MIGRATIONS, "meta", "_journal.json"))) return;
  // The two migrators differ only in the driver type; at run time each gets its own driver's database.
  if (isHostedDb()) await migratePostgres(getDb() as Parameters<typeof migratePostgres>[0], { migrationsFolder: MIGRATIONS });
  else await migratePglite(getDb() as Parameters<typeof migratePglite>[0], { migrationsFolder: MIGRATIONS });
}
