import { existsSync } from "node:fs";
import path from "node:path";
import { migrate } from "drizzle-orm/pglite/migrator";
import { getDb } from "./client";

const MIGRATIONS = path.join(process.cwd(), "drizzle");

// Applies every file in drizzle/meta/_journal.json in order: 0000_init.sql (generated by
// `npm run db:generate`) and 0001_rules.sql (hand-written triggers and the task_outcome view).
// Safe to call on every start: drizzle records applied migrations and skips them.
export async function runMigrations() {
  if (!existsSync(path.join(MIGRATIONS, "meta", "_journal.json"))) return;
  await migrate(getDb(), { migrationsFolder: MIGRATIONS });
}
